# Default values for helm-webapp-cve-consumer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
minReadySeconds: 5
image:
  initContainer:
    repository: niteshmore22/webapp-cve-processor-db
    pullPolicy: Always
    tag: "latest"
  main:  
    repository: niteshmore22/webapp-cve-consumer
    pullPolicy: Always
    tag: "latest"
imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: ZW50ZXJ5b3VydXNlcm5hbWVwYXNzd29yZA==
namespace: "cve-consumer"
nameOverride: ""
fullnameOverride: "cve-consumer"

livenessProbe:
  httpGet:
    path: /liveness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1     

# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

resources: 
  limits:
   memory: "512Mi"
   cpu: "1" 
  requests:
    memory: "256Mi"
    cpu: "500m"

Strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  progressDeadlineSeconds: 300

configMap:
  db_host: cve-postgresql.cve-consumer.svc.cluster.local
  db_port: "5432"
  app_port: "8080"
  db_name: cve
  db_schemas : cve
  kafka_topic: cve
  kafka_group_id: cve-group
  kafka_brokers: 
  - localhost:9092
  - localhost:9093
  - localhost:9094


secrets:
  type: Opaque
  db_username: username
  db_password: password
  kafka_username: username
  kafka_password: password