# Default values for helm-webapp-cve-consumer.
nameOverride: ""
fullnameOverride: cve-consumer
namespace: cve-consumer

podLabels: 
  app: cve-consumer
  service: kafka-consumer

replicaCount: 3
minReadySeconds: 5
progressDeadlineSeconds: 300

image:
  initContainer:
    repository: niteshmore22/webapp-cve-processor-db
    pullPolicy: Always
    tag: "latest"
  main:  
    repository: niteshmore22/webapp-cve-consumer
    pullPolicy: Always
    tag: "latest"

imagePullSecrets:
    type: kubernetes.io/dockerconfigjson
    name: regcred
    dockerconfigjson: ZW50ZXJ5b3VydXNlcm5hbWVwYXNzd29yZA==

livenessProbe:
  httpGet:
    path: /liveness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1

resources: 
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 0.5
    memory: 256Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

configMap:
  db_host: cve-postgresql.cve-consumer.svc.cluster.local
  db_port: "5432"
  app_port: "8080"
  db_name: cve
  db_schemas : cve
  kafka_topic: cve
  kafka_group_id: cve-group
  kafka_brokers: 
    - localhost:9092
    - localhost:9093
    - localhost:9094

secrets:
  type: Opaque
  db_username: username
  db_password: password
  kafka_username: username
  kafka_password: password

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - cve-consumer
        topologyKey: "kubernetes.io/hostname"

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPU: 80
  # targetMemory: 60

pdb:
  create: true
  maxUnavailable: 1