apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace | quote}}
  name: {{ include "helm-webapp-cve-consumer.fullname" . }}
  labels:
    {{- include "helm-webapp-cve-consumer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "helm-webapp-cve-consumer.selectorLabels" . | nindent 6 }}
  Strategy:
    type: {{ .Values.Strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.Strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.Strategy.rollingUpdate.maxUnavailable }}
    progressDeadlineSeconds: {{ .Values.Strategy.progressDeadlineSeconds }} 
  template:
    metadata:
      labels:
        {{- include "helm-webapp-cve-consumer.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-regcred
      initContainers:
        - name: {{ .Chart.Name }}-init-db
          image: "{{ .Values.image.initContainer.repository }}:{{ .Values.image.initContainer.tag }}"
          imagePullPolicy: {{ .Values.image.initContainer.pullPolicy }}
          env:
            - name: db_host
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_host
            - name: db_port
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_port              
            - name: db_name
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_name
            - name: db_url
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_url
            - name: db_user
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db_username
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db_password
            - name: db_schemas
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_schemas        
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.main.repository }}:{{ .Values.image.main.tag }}"
          imagePullPolicy: {{ .Values.image.main.pullPolicy }}
          env:
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: kafka_topic
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: kafka_brokers
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: kafka_group_id
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db_password       
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_name   
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_port
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: app_port                      
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-cm
                  key: db_host
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: kafka_username 
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: kafka_password                                                                       
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}