---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
  namespace: {{ .Values.namespace | quote}}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: {{ .Values.imagePullSecrets.type }}
